version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: crypto
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A backend worker -l info
    depends_on:
      - redis
      - db
      - web